version: "3.9"
services:
  jupyter:
    container_name: "jp"
    build:
      context: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "8888:8888"
    volumes:
      - ..:/tf
      - ../../small-data:/small-data
      - ../../small-data-test:/small-data-test
      - ../../big-data:/big-data
      - ../../big-data-test:/big-data-test
    user: "1000:1000"
    entrypoint: jupyter notebook --allow-root --ip='0.0.0.0' --notebook-dir='/tf'
  tensorboard:
    container_name: "tb"
    image: "tensorflow/tensorflow:nightly-gpu-jupyter"
    ports:
      - "6006:6006"
    volumes:
      - ../logs:/logs
    user: "1000:1000"
    entrypoint: tensorboard --logdir=../logs --host 0.0.0.0