version: "3.9"
services:
  jupyter:
    user: "1002:1002"
    container_name: "jp"
    build:
      context: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "8888:8888"
    volumes:
      - ..:/tf
      - ../../data1000:/data1000
      - ../../data1000-test:/data1000-test
    entrypoint: jupyter notebook --allow-root --ip='0.0.0.0' --notebook-dir='/tf'
  tensorboard:
    user: "1002:1002"
    container_name: "tb"
    image: "tensorflow/tensorflow:nightly-gpu-jupyter"
    ports:
      - "6006:6006"
    volumes:
      - ../logs:/logs
    entrypoint: tensorboard --logdir=../logs --host 0.0.0.0